const reviewData = {
    "battlemaster01": {
        "1": { nick: "gamer123", star: 5, review: "정말 최고의 게임이에요! 친구들과 함께 하기에 완벽합니다.", regDate: "2024-07-01" },
        "2": { nick: "beginnergamer", star: 4, review: "그래픽이 정말 멋져요. 게임 플레이도 아주 재미있습니다.", regDate: "2024-07-02" },
        "3": { nick: "proplayer", star: 5, review: "매일매일 즐기고 있습니다. 최고예요!", regDate: "2024-07-03" },
        "4": { nick: "casualgamer", star: 3, review: "가끔 버그가 있어요, 그래도 재미있습니다.", regDate: "2024-07-04" },
        "5": { nick: "hardcorefan", star: 5, review: "친구들과 함께 하는 시간이 최고입니다.", regDate: "2024-07-05" },
        "6": { nick: "strategist", star: 4, review: "전략적으로 접근할 수 있는 요소가 마음에 듭니다.", regDate: "2024-07-06" },
        "7": { nick: "shooter", star: 3, review: "사격 감각이 좋습니다만, 개선의 여지가 있어요.", regDate: "2024-07-07" },
        "8": { nick: "newbie", star: 4, review: "초보자도 쉽게 즐길 수 있어요.", regDate: "2024-07-08" },
        "9": { nick: "veteran", star: 5, review: "오랜 시간 즐기고 있습니다. 만족스러워요.", regDate: "2024-07-09" },
        "10": { nick: "sniper", star: 5, review: "정밀한 사격의 재미가 있습니다.", regDate: "2024-07-10" }
    },
    "gamefanatic02": {
        "1": { nick: "contestant", star: 3, review: "게임은 재미있지만, 버그가 가끔 있어서 조금 아쉽습니다.", regDate: "2024-07-03" },
        "2": { nick: "gamegenius", star: 5, review: "최고의 게임이에요! 매일매일 플레이하고 있어요.", regDate: "2024-07-04" },
        "3": { nick: "challenger", star: 4, review: "도전하는 재미가 있어요. 계속 플레이하게 됩니다.", regDate: "2024-07-05" },
        "4": { nick: "maverick", star: 2, review: "그래픽은 좋지만, 게임 플레이가 단조롭습니다.", regDate: "2024-07-06" },
        "5": { nick: "legend", star: 5, review: "전설적인 게임입니다. 누구에게나 추천합니다.", regDate: "2024-07-07" },
        "6": { nick: "rookie", star: 3, review: "초보자에게 적합하지만, 숙련자에게는 조금 아쉽습니다.", regDate: "2024-07-08" },
        "7": { nick: "vanguard", star: 4, review: "게임의 깊이가 있어요. 전략적으로 플레이할 수 있습니다.", regDate: "2024-07-09" },
        "8": { nick: "wizard", star: 5, review: "마법 같은 게임 경험을 제공합니다. 아주 만족합니다.", regDate: "2024-07-10" },
        "9": { nick: "warrior", star: 4, review: "전투가 아주 재미있습니다. 지속적으로 즐기게 됩니다.", regDate: "2024-07-11" },
        "10": { nick: "sorcerer", star: 5, review: "마법 시스템이 아주 훌륭합니다. 강력 추천합니다.", regDate: "2024-07-12" }
    },
    "hunter03": {
        "1": { nick: "playerone", star: 4, review: "다양한 맵과 무기 덕분에 질리지 않고 계속 즐길 수 있어요.", regDate: "2024-07-05" },
        "2": { nick: "reviewking", star: 2, review: "처음엔 재미있었지만, 점점 반복적이어서 지루해지네요.", regDate: "2024-07-06" },
        "3": { nick: "expert", star: 5, review: "전문가 수준의 게임 플레이를 즐길 수 있습니다.", regDate: "2024-07-07" },
        "4": { nick: "novice", star: 3, review: "초보자에게도 친절한 게임입니다. 하지만 더 발전이 필요해요.", regDate: "2024-07-08" },
        "5": { nick: "hero", star: 4, review: "영웅적인 캐릭터와 스토리가 마음에 들어요.", regDate: "2024-07-09" },
        "6": { nick: "villain", star: 2, review: "악당 역할이 기대 이하입니다. 개선이 필요해요.", regDate: "2024-07-10" },
        "7": { nick: "champion", star: 5, review: "챔피언이 될 수 있는 기회가 많아서 좋아요.", regDate: "2024-07-11" },
        "8": { nick: "guardian", star: 4, review: "수호자 역할을 하며 팀을 이끌 수 있어요.", regDate: "2024-07-12" },
        "9": { nick: "assassin", star: 3, review: "암살자 캐릭터가 재미있지만, 조작이 어려워요.", regDate: "2024-07-13" },
        "10": { nick: "scout", star: 4, review: "정찰 임무가 흥미롭고, 다양한 전략을 사용할 수 있습니다.", regDate: "2024-07-14" }
    },
    "progamer04": {
        "1": { nick: "powergamer", star: 1, review: "서버 문제가 너무 많아서 게임을 즐기기 힘들어요.", regDate: "2024-07-07" },
        "2": { nick: "gamemaster", star: 5, review: "게임 플레이와 전략성이 최고예요. 정말 추천합니다!", regDate: "2024-07-08" },
        "3": { nick: "dominant", star: 5, review: "압도적인 재미를 제공하는 게임입니다. 최고예요!", regDate: "2024-07-09" },
        "4": { nick: "pioneer", star: 4, review: "개척자 정신으로 즐길 수 있는 게임입니다.", regDate: "2024-07-10" },
        "5": { nick: "innovator", star: 3, review: "혁신적인 요소가 있지만, 아직 부족한 부분이 있습니다.", regDate: "2024-07-11" },
        "6": { nick: "trailblazer", star: 2, review: "처음엔 흥미로웠지만, 빠르게 질립니다.", regDate: "2024-07-12" },
        "7": { nick: "visionary", star: 5, review: "비전이 뛰어난 게임입니다. 강력 추천!", regDate: "2024-07-13" },
        "8": { nick: "strategist", star: 4, review: "전략적으로 접근할 수 있는 게임입니다. 만족합니다.", regDate: "2024-07-14" },
        "9": { nick: "champion", star: 5, review: "챔피언이 될 수 있는 요소가 많아서 좋아요.", regDate: "2024-07-15" },
        "10": { nick: "defender", star: 4, review: "방어적인 요소가 잘 되어 있어요. 재미있습니다.", regDate: "2024-07-16" }
    },
    "gamelover05": {
        "1": { nick: "gamelover", star: 3, review: "전체적으로 괜찮지만, 몇몇 업데이트가 필요합니다.", regDate: "2024-07-09" },
        "2": { nick: "battlequeen", star: 5, review: "친구들과 함께하는 시간이 너무 즐거워요. 계속 하고 싶어요.", regDate: "2024-07-10" },
        "3": { nick: "adventurer", star: 4, review: "모험 요소가 많아서 즐겁습니다.", regDate: "2024-07-11" },
        "4": { nick: "wanderer", star: 3, review: "여정을 즐길 수 있지만, 조금 단조로워요.", regDate: "2024-07-12" },
        "5": { nick: "explorer", star: 5, review: "탐험하는 재미가 최고입니다.", regDate: "2024-07-13" },
        "6": { nick: "seeker", star: 4, review: "발견하는 재미가 있는 게임입니다.", regDate: "2024-07-14" },
        "7": { nick: "journeyman", star: 3, review: "여정을 즐길 수 있지만, 개선의 여지가 있습니다.", regDate: "2024-07-15" },
        "8": { nick: "pilgrim", star: 2, review: "처음에는 좋았지만, 반복적인 요소가 많습니다.", regDate: "2024-07-16" },
        "9": { nick: "voyager", star: 4, review: "여정을 즐길 수 있는 다양한 요소가 있습니다.", regDate: "2024-07-17" },
        "10": { nick: "navigator", star: 5, review: "항해하는 기분으로 즐길 수 있습니다.", regDate: "2024-07-18" }
    },
    "sniper06": {
        "1": { nick: "sharpshooter", star: 4, review: "정밀한 사격과 전략적 플레이가 정말 재미있습니다.", regDate: "2024-07-11" },
        "2": { nick: "headshotking", star: 5, review: "헤드샷의 쾌감이 대단해요! 강력 추천합니다.", regDate: "2024-07-12" },
        "3": { nick: "marksman", star: 5, review: "사격의 정교함이 놀랍습니다. 매우 만족합니다.", regDate: "2024-07-13" },
        "4": { nick: "scout", star: 3, review: "정찰 임무가 재미있지만, 개선이 필요해요.", regDate: "2024-07-14" },
        "5": { nick: "sniperelite", star: 5, review: "최고의 저격 경험을 제공합니다. 강력 추천!", regDate: "2024-07-15" },
        "6": { nick: "longshot", star: 4, review: "장거리 사격의 재미가 있습니다.", regDate: "2024-07-16" },
        "7": { nick: "triggerhappy", star: 3, review: "트리거 반응이 좋아요. 하지만 더 개선이 필요합니다.", regDate: "2024-07-17" },
        "8": { nick: "sniperkiller", star: 5, review: "저격의 재미가 아주 큽니다. 만족합니다.", regDate: "2024-07-18" },
        "9": { nick: "deadeye", star: 4, review: "정확한 사격이 가능해서 재미있습니다.", regDate: "2024-07-19" },
        "10": { nick: "silentkiller", star: 5, review: "은밀하게 적을 제거하는 재미가 있어요.", regDate: "2024-07-20" }
    },
    "strategist07": {
        "1": { nick: "tactician", star: 4, review: "전략적으로 게임을 풀어나가는 재미가 일품입니다.", regDate: "2024-07-13" },
        "2": { nick: "warplanner", star: 3, review: "전반적으로 재미있지만, 약간의 개선이 필요해요.", regDate: "2024-07-14" },
        "3": { nick: "thinker", star: 4, review: "생각하면서 즐길 수 있는 게임입니다.", regDate: "2024-07-15" },
        "4": { nick: "schemer", star: 5, review: "계획을 세워서 진행하는 재미가 있습니다.", regDate: "2024-07-16" },
        "5": { nick: "strategist", star: 5, review: "전략적인 요소가 잘 반영된 게임입니다.", regDate: "2024-07-17" },
        "6": { nick: "planner", star: 4, review: "계획적으로 접근할 수 있어서 좋습니다.", regDate: "2024-07-18" },
        "7": { nick: "mastermind", star: 5, review: "뛰어난 전략성을 갖춘 게임입니다. 매우 만족해요.", regDate: "2024-07-19" },
        "8": { nick: "tacticianmaster", star: 4, review: "전략적으로 접근할 수 있는 요소가 많아서 재미있어요.", regDate: "2024-07-20" },
        "9": { nick: "commander", star: 5, review: "지휘하는 재미가 있는 게임입니다. 매우 만족합니다.", regDate: "2024-07-21" },
        "10": { nick: "general", star: 4, review: "전체적인 전략을 세우는 재미가 있습니다.", regDate: "2024-07-22" }
    },
    "tank08": {
        "1": { nick: "heavymetal", star: 5, review: "무거운 무기를 들고 전장을 누비는 기분이 최고입니다.", regDate: "2024-07-15" },
        "2": { nick: "ironclad", star: 4, review: "게임이 전반적으로 훌륭합니다. 다만 몇 가지 버그가 있어요.", regDate: "2024-07-16" },
        "3": { nick: "armored", star: 5, review: "장갑차를 몰며 적을 물리치는 재미가 큽니다.", regDate: "2024-07-17" },
        "4": { nick: "steelbeast", star: 4, review: "강철 같은 캐릭터가 마음에 듭니다.", regDate: "2024-07-18" },
        "5": { nick: "warrior", star: 5, review: "전쟁터에서 싸우는 기분이 최고입니다.", regDate: "2024-07-19" },
        "6": { nick: "tankmaster", star: 4, review: "탱크를 몰면서 전장을 지배하는 재미가 있습니다.", regDate: "2024-07-20" },
        "7": { nick: "battletank", star: 5, review: "배틀 탱크를 몰며 적을 물리치는 기분이 최고예요.", regDate: "2024-07-21" },
        "8": { nick: "ironshield", star: 4, review: "강력한 방어력으로 적의 공격을 막아냅니다.", regDate: "2024-07-22" },
        "9": { nick: "steelwall", star: 5, review: "철벽 방어의 재미가 있습니다. 매우 만족해요.", regDate: "2024-07-23" },
        "10": { nick: "battlehardened", star: 4, review: "전장에서 싸우는 재미가 큽니다.", regDate: "2024-07-24" }
    },
    "medic09": {
        "1": { nick: "healer", star: 3, review: "치료 역할이 중요하지만, 개선될 부분이 많습니다.", regDate: "2024-07-17" },
        "2": { nick: "lifesaver", star: 5, review: "팀원을 살리는 기분이 정말 좋아요. 매우 만족합니다.", regDate: "2024-07-18" },
        "3": { nick: "doctor", star: 4, review: "의료진 역할을 수행하는 재미가 있습니다.", regDate: "2024-07-19" },
        "4": { nick: "paramedic", star: 3, review: "응급 의료 상황을 다루는 재미가 있어요.", regDate: "2024-07-20" },
        "5": { nick: "surgeon", star: 5, review: "수술실의 긴장감을 게임에서 느낄 수 있습니다.", regDate: "2024-07-21" },
        "6": { nick: "nurse", star: 4, review: "간호사 역할을 수행하는 재미가 있습니다.", regDate: "2024-07-22" },
        "7": { nick: "responder", star: 3, review: "긴급 상황에 대처하는 재미가 있습니다.", regDate: "2024-07-23" },
        "8": { nick: "medicmaster", star: 5, review: "의료진 역할을 완벽히 수행할 수 있습니다.", regDate: "2024-07-24" },
        "9": { nick: "firstaid", star: 4, review: "응급 처치를 하는 재미가 있습니다.", regDate: "2024-07-25" },
        "10": { nick: "healthcare", star: 5, review: "헬스케어 시스템이 잘 되어 있어요. 매우 만족합니다.", regDate: "2024-07-26" }
    },
    "scout10": {
        "1": { nick: "pathfinder", star: 4, review: "정찰 임무가 재미있고 유용해요. 게임의 깊이가 있습니다.", regDate: "2024-07-19" },
        "2": { nick: "trailblazer", star: 2, review: "처음엔 흥미로웠지만, 빠르게 질립니다.", regDate: "2024-07-20" },
        "3": { nick: "tracker", star: 4, review: "추적하는 재미가 있습니다. 다양한 전략을 사용할 수 있어요.", regDate: "2024-07-21" },
        "4": { nick: "explorer", star: 5, review: "탐험의 재미가 있습니다. 매우 만족해요.", regDate: "2024-07-22" },
        "5": { nick: "guide", star: 3, review: "가이드를 따라가며 진행하는 재미가 있어요.", regDate: "2024-07-23" },
        "6": { nick: "spotter", star: 4, review: "적을 발견하고 팀에 알리는 재미가 있습니다.", regDate: "2024-07-24" },
        "7": { nick: "observer", star: 5, review: "주변을 관찰하고 정보를 수집하는 재미가 큽니다.", regDate: "2024-07-25" },
        "8": { nick: "navigator", star: 3, review: "지도를 보고 길을 찾는 재미가 있어요.", regDate: "2024-07-26" },
        "9": { nick: "seeker", star: 4, review: "숨겨진 보물을 찾는 재미가 있습니다.", regDate: "2024-07-27" },
        "10": { nick: "lookout", star: 5, review: "전망대에서 적을 감시하는 재미가 큽니다.", regDate: "2024-07-28" }
        },
        "kingking": {
            "11": { nick: "pathfinder", star: 4, review: "정찰 임무가 재미있고 유용해요. 게임의 깊이가 있습니다.", regDate: "2024-07-19" },
            "12": { nick: "trailblazer", star: 2, review: "처음엔 흥미로웠지만, 빠르게 질립니다.", regDate: "2024-07-20" },
            "13": { nick: "tracker", star: 4, review: "추적하는 재미가 있습니다. 다양한 전략을 사용할 수 있어요.", regDate: "2024-07-21" },
            "14": { nick: "explorer", star: 5, review: "탐험의 재미가 있습니다. 매우 만족해요.", regDate: "2024-07-22" },
            "15": { nick: "guide", star: 3, review: "가이드를 따라가며 진행하는 재미가 있어요.", regDate: "2024-07-23" },
            "16": { nick: "spotter", star: 4, review: "적을 발견하고 팀에 알리는 재미가 있습니다.", regDate: "2024-07-24" },
            "17": { nick: "observer", star: 5, review: "주변을 관찰하고 정보를 수집하는 재미가 큽니다.", regDate: "2024-07-25" },
            "18": { nick: "navigator", star: 3, review: "지도를 보고 길을 찾는 재미가 있어요.", regDate: "2024-07-26" },
            "19": { nick: "seeker", star: 4, review: "숨겨진 보물을 찾는 재미가 있습니다.", regDate: "2024-07-27" },
            "20": { nick: "lookout", star: 5, review: "전망대에서 적을 감시하는 재미가 큽니다.", regDate: "2024-07-28" }
        },
        "warriorhero": {
            "11": { nick: "fighter", star: 4, review: "전투가 흥미진진하고, 매우 재미있습니다.", regDate: "2024-07-19" },
            "12": { nick: "defender", star: 3, review: "방어하는 재미가 있지만, 조금 단조롭습니다.", regDate: "2024-07-20" },
            "13": { nick: "berserker", star: 5, review: "광전사 캐릭터가 정말 멋집니다.", regDate: "2024-07-21" },
            "14": { nick: "gladiator", star: 4, review: "검투사의 전투가 아주 흥미로워요.", regDate: "2024-07-22" },
            "15": { nick: "knight", star: 5, review: "기사의 명예와 용기가 잘 표현되어 있습니다.", regDate: "2024-07-23" },
            "16": { nick: "paladin", star: 3, review: "성기사의 역할이 조금 아쉽습니다.", regDate: "2024-07-24" },
            "17": { nick: "warrior", star: 4, review: "전사 캐릭터가 매우 재미있어요.", regDate: "2024-07-25" },
            "18": { nick: "swordsman", star: 5, review: "검술의 재미가 최고입니다.", regDate: "2024-07-26" },
            "19": { nick: "barbarian", star: 4, review: "야만인의 전투가 매우 인상적입니다.", regDate: "2024-07-27" },
            "20": { nick: "viking", star: 5, review: "바이킹의 모험이 정말 흥미로워요.", regDate: "2024-07-28" }
        },
        "sharpshooter": {
            "11": { nick: "marksman", star: 4, review: "정확한 사격이 매우 만족스럽습니다.", regDate: "2024-07-19" },
            "12": { nick: "sniper", star: 5, review: "저격의 쾌감이 정말 대단해요.", regDate: "2024-07-20" },
            "13": { nick: "gunner", star: 3, review: "총기의 반동이 조금 아쉽습니다.", regDate: "2024-07-21" },
            "14": { nick: "shooter", star: 4, review: "사격의 재미가 있습니다.", regDate: "2024-07-22" },
            "15": { nick: "hunter", star: 5, review: "사냥의 재미가 최고입니다.", regDate: "2024-07-23" },
            "16": { nick: "rifleman", star: 3, review: "소총의 반동이 조금 강합니다.", regDate: "2024-07-24" },
            "17": { nick: "gunslinger", star: 4, review: "총잡이 캐릭터가 아주 재미있어요.", regDate: "2024-07-25" },
            "18": { nick: "commando", star: 5, review: "코만도의 액션이 매우 인상적입니다.", regDate: "2024-07-26" },
            "19": { nick: "mercenary", star: 4, review: "용병의 전투가 매우 흥미롭습니다.", regDate: "2024-07-27" },
            "20": { nick: "sniperelite", star: 5, review: "저격 엘리트의 정확성이 최고입니다.", regDate: "2024-07-28" }
        },
        "gameenthusiast": {
            "11": { nick: "fanatic", star: 5, review: "게임을 정말 사랑합니다. 매우 재미있어요.", regDate: "2024-07-19" },
            "12": { nick: "addict", star: 4, review: "중독성이 강해서 계속 하게 됩니다.", regDate: "2024-07-20" },
            "13": { nick: "lover", star: 3, review: "사랑하지만, 개선의 여지가 있습니다.", regDate: "2024-07-21" },
            "14": { nick: "freak", star: 5, review: "게임을 즐기는 데 있어서 최고입니다.", regDate: "2024-07-22" },
            "15": { nick: "junkie", star: 4, review: "게임의 재미가 너무 커서 자주 하게 됩니다.", regDate: "2024-07-23" },
            "16": { nick: "maniac", star: 3, review: "열광적이지만, 약간의 단점도 있어요.", regDate: "2024-07-24" },
            "17": { nick: "devotee", star: 5, review: "헌신적으로 즐기고 있습니다.", regDate: "2024-07-25" },
            "18": { nick: "aficionado", star: 4, review: "매우 좋아하지만, 몇 가지 아쉬움이 있습니다.", regDate: "2024-07-26" },
            "19": { nick: "buff", star: 3, review: "전체적으로 좋지만, 개선이 필요해요.", regDate: "2024-07-27" },
            "20": { nick: "enthusiast", star: 5, review: "게임을 정말 좋아해서 매우 만족합니다.", regDate: "2024-07-28" }
        },
        "arcademaster": {
            "11": { nick: "gamerpro", star: 5, review: "프로 게이머로서 매우 만족합니다.", regDate: "2024-07-19" },
            "12": { nick: "arcadechamp", star: 4, review: "아케이드 게임 챔피언입니다. 매우 재미있어요.", regDate: "2024-07-20" },
            "13": { nick: "coinplayer", star: 3, review: "코인 투입식 게임이지만, 재미있어요.", regDate: "2024-07-21" },
            "14": { nick: "arcadelover", star: 5, review: "아케이드 게임을 사랑합니다. 최고예요.", regDate: "2024-07-22" },
            "15": { nick: "joystickhero", star: 4, review: "조이스틱 조작이 재미있습니다.", regDate: "2024-07-23" },
            "16": { nick: "buttonmasher", star: 3, review: "버튼을 많이 누르는 게임이지만, 재미있어요.", regDate: "2024-07-24" },
            "17": { nick: "tokenmaster", star: 5, review: "토큰으로 하는 게임이 아주 재미있습니다.", regDate: "2024-07-25" },
            "18": { nick: "arcadefan", star: 4, review: "아케이드 게임 팬으로서 매우 만족해요.", regDate: "2024-07-26" },
            "19": { nick: "classicgamer", star: 3, review: "클래식 게임 느낌이지만, 개선이 필요해요.", regDate: "2024-07-27" },
            "20": { nick: "pinballwizard", star: 5, review: "핀볼 게임이 최고예요. 강력 추천합니다.", regDate: "2024-07-28" }
        },
        "speedrunner": {
            "11": { nick: "fastplayer", star: 4, review: "빠르게 진행할 수 있어 좋습니다.", regDate: "2024-07-19" },
            "12": { nick: "timerunner", star: 3, review: "시간 제한이 조금 아쉽습니다.", regDate: "2024-07-20" },
            "13": { nick: "speedchamp", star: 5, review: "속도감이 최고입니다. 매우 만족해요.", regDate: "2024-07-21" },
            "14": { nick: "racer", star: 4, review: "레이싱 게임으로서 매우 재미있습니다.", regDate: "2024-07-22" },
            "15": { nick: "dashmaster", star: 5, review: "질주하는 재미가 있습니다.", regDate: "2024-07-23" },
            "16": { nick: "sprintking", star: 3, review: "단거리 경주 느낌이 조금 아쉽습니다.", regDate: "2024-07-24" },
            "17": { nick: "fastandfurious", star: 4, review: "속도감 있는 게임 플레이가 좋습니다.", regDate: "2024-07-25" },
            "18": { nick: "quickgamer", star: 5, review: "빠른 진행이 매우 만족스럽습니다.", regDate: "2024-07-26" },
            "19": { nick: "speedster", star: 4, review: "속도감 있는 게임을 좋아합니다.", regDate: "2024-07-27" },
            "20": { nick: "timeattack", star: 5, review: "타임어택 모드가 최고입니다.", regDate: "2024-07-28" }
        },
        "adventureseeker": {
            "11": { nick: "explorer", star: 5, review: "탐험의 재미가 큽니다. 매우 만족해요.", regDate: "2024-07-19" },
            "12": { nick: "wanderer", star: 4, review: "여행하는 기분으로 즐길 수 있어요.", regDate: "2024-07-20" },
            "13": { nick: "voyager", star: 3, review: "모험의 재미가 있지만, 조금 단조롭습니다.", regDate: "2024-07-21" },
            "14": { nick: "pilgrim", star: 5, review: "순례자의 길을 따라가는 재미가 있어요.", regDate: "2024-07-22" },
            "15": { nick: "nomad", star: 4, review: "유목민의 생활을 체험할 수 있습니다.", regDate: "2024-07-23" },
            "16": { nick: "traveler", star: 3, review: "여행자의 시각에서 즐길 수 있어요.", regDate: "2024-07-24" },
            "17": { nick: "adventurer", star: 5, review: "모험의 재미가 아주 큽니다. 강력 추천해요.", regDate: "2024-07-25" },
            "18": { nick: "rover", star: 4, review: "여행하면서 다양한 경험을 할 수 있습니다.", regDate: "2024-07-26" },
            "19": { nick: "trekker", star: 3, review: "트레킹의 재미가 있지만, 개선이 필요해요.", regDate: "2024-07-27" },
            "20": { nick: "journeyman", star: 5, review: "여정의 끝을 향해가는 재미가 큽니다.", regDate: "2024-07-28" }
        },
        "strategypro": {
            "11": { nick: "tactician", star: 4, review: "전략을 세워서 플레이하는 재미가 큽니다.", regDate: "2024-07-19" },
            "12": { nick: "planner", star: 3, review: "계획을 세우는 재미가 있지만, 단조로워요.", regDate: "2024-07-20" },
            "13": { nick: "strategist", star: 5, review: "전략적인 요소가 많아서 재미있습니다.", regDate: "2024-07-21" },
            "14": { nick: "commander", star: 4, review: "지휘하는 재미가 큽니다.", regDate: "2024-07-22" },
            "15": { nick: "general", star: 3, review: "전체적인 전략을 세우는 재미가 있지만, 아쉬움이 있어요.", regDate: "2024-07-23" },
            "16": { nick: "mastermind", star: 5, review: "뛰어난 전략성을 갖춘 게임입니다.", regDate: "2024-07-24" },
            "17": { nick: "schemer", star: 4, review: "계획을 세워서 진행하는 재미가 큽니다.", regDate: "2024-07-25" },
            "18": { nick: "visionary", star: 3, review: "비전이 뛰어나지만, 약간의 단점이 있습니다.", regDate: "2024-07-26" },
            "19": { nick: "innovator", star: 5, review: "혁신적인 요소가 많아서 재미있습니다.", regDate: "2024-07-27" },
            "20": { nick: "trailblazer", star: 4, review: "새로운 길을 개척하는 재미가 큽니다.", regDate: "2024-07-28" }
        }
    };


export default reviewData;